### ISSUE TITLE
app.jsにエラーがあって振っても止まらない

### ISSUE THREAD

**Issue by youten** [meco300/AlarmAppForFirefoxOS#1]
・sensorArea.innerHTMLにshakeの強さを出力してるらしきところがエラーでシェイクが判定されない
・それと手動で止めるとdevicemotionのイベントハンドラremoveされないように見える

**Comment by meco300** [comment]
index.html側でsensorAreaを削除したのにjs側は削除されてませんでした。
js側の記述も削除しました。
